message: "Today we start building the first pus/sass website"
meta:
  title: Speed4Courier
  description: Salut
form:
  top:
    formTitle: Get a Quote
    goTo:
      label: Request a Callback
      id: p4j1eU4x
    formID: V1JRDgaa
    formDescription: We can move anything for you, from a small packet to multiple pallets.
  bottom:
    formTitle: Request a Callback
    formID: p4j1eU4x
    goTo:
      label: Get a Quote
      id: V1JRDgaa
    formDescription: We are a friendly and helpful same day courier company with vehicles across the country available to collect within the hour of your call.
content:
  contentKeyList:
    - home
    - about
    - fleet
    - services
    - quote
  home:
    title: Speed4Couriers
    description:
  about:
    title: We can move anything
    description:
      - Founded in Manchester in 2020, Speed4courier has grown to become one of the north's leading Same Day couriers.
      - The group runs an extensive fleet of vans and wagons, with strong presence across the North's major towns & cities and the M62 corridor.
      - We have long standing relationships in place with many of the UK's leading transport  firms.
  fleet:
    title: Please choose what vehicle size you need
    description: We also specialise in the movement of high value and fragile goods.
