message: "Today we start building the first pus/sass website"
meta:
  title: Speed4Courier
  description: Salut
form:
  top:
    formTitle: Speed4Courier
    formID: V1JRDgaa
    quoteClass: callback
    goTo:
      label: Get a Quote
      id: p4j1eU4x
    formDescription: We can move anything for you, from a small packet to multiple pallets.
  bottom:
    quoteClass: quote
    formTitle: Same Day Couriers
    formID: p4j1eU4x
    goTo:
      label: Request a Callback
      id: V1JRDgaa
    formDescription: Get a fast and reliable same-day courier service
content:
  contentKeyList:
    - callback
    - about
    - fleet
    - services
    - quote
  services:
    description:
      - Same Day Courier Services
      - European Same Day Courier
      - Urgent Courier Service
      - Emergency Courier
      - Same Night Courier Service
      - Time Critical Courier
      - Over Night Dedicated
      - International Courier
      - Wait And Return Courier
      - Dedicated Direct Drive Delivery
      - Secure Courier Service
      - Refrigerated Courier Service
      - Exhibition and Event Courier
  about:
    title: We can move anything
    description:
      - Founded in Manchester in 2020, Speed4courier has grown to become one of the north's leading Same Day couriers.
      - The group runs an extensive fleet of vans and wagons, with strong presence across the North's major towns & cities and the M62 corridor.
      - We have long standing relationships in place with many of the UK's leading transport  firms.
    carousel:
      - amazon.png
      - ceva.png
      - dhl.png
      - nhs.png
      - sonos.png
      - xpo.png
  fleet:
    title: Please choose what vehicle size you need
    description: We also specialise in the movement of high value and fragile goods.
    vehicle:
      - van: small van11.jpg
        title: Small Van (SV)
        length: 120cm
        width: 100cm
        height: 100cm
        payload: 450kg
        description: Carries 1 Standard UK Pallet

      - van: Swb1.jpg
        title: Short Wheel Based Van (SWB)
        length: 240cm
        width: 100cm
        height: 120cm
        payload: 800kg
        description: Carries 2 Standard UK Pallets

      - van: long.jpg
        title: Long Wheel Based Van (LWB)
        length: 340cm
        width: 120cm
        height: 180cm
        payload: 1200kg
        description: Carries 3 Standard UK Pallets

      - van: xlwb.jpg
        title: Extra-Long Wheel Based Van (XLWB)
        length: 420cm
        width: 120cm
        height: 180cm
        payload: 1000kg
        description: Carries 4 Standard UK Pallets

      - van: luton.jpg
        title: Luton Van
        length: 400cm
        width: 200cm
        height: 200cm
        payload: 1000kg
        description: Carries 6 Standard UK Pallets Box, Curtain and Tail Lift Options Available

      - van: 7.5.jpg
        title: 7.5 Tonne (7.5T)
        length: 240cm
        width: 100cm
        height: 120cm
        payload: 800kg
        description: Carries 10 Standard UK Pallets Box, Curtain and Tail Lift Options Available

      - van: 18 t.jpg
        title: 18 Tonne (18T)
        length: 700cm
        width: 240cm
        height: 250cm
        payload: 9000kg
        description: Carries 14 Standard UK Pallets Box, Curtain and Tail Lift Options Available

      - van: 26t.jpg
        title: 26 Tonne (26T)
        length: 800cm
        width: 240cm
        height: 250cm
        payload: 15000kg
        description: Carries 16 Standard UK Pallets Box, Curtain and Tail Lift Options Available

      - van: artic1.jpg
        title: Artic
        length: 1360cm
        width: 250cm
        height: 260cm
        payload: 26000kg
        description: Carries 26 Standard UK Pallets Box,Curtain and Tail Lift Options Available
