message: "Today we start building the first pus/sass website"
meta:
  title: Speed4Courier
  description: We can move anything for you from a small packet to multiple pallets.
content:
  contentKeyList:
    - home
    - about
    - fleet
    - services
  home:
    title: Speed4Couriers
    description:
      - Founded in Manchester in 2020, Speed4courier has grown to become one of the north's leading Same Day couriers.
      - The group runs an extensive fleet of vans and wagons, with strong presence across the North's major towns & cities and the M62 corridor.
      - We have long standing relationships in place with many of the UK's leading transport  firms.
      - We can move anything for you from a small packet to multiple pallets.
  about:
    title: We can move anything
    description:
      - We also specialise in the movement of high value and fragile goods.
      - We are a friendly and helpful same day courier company with vehicles across the country available to collect within the hour of your call.
  fleet:
    title: Please choose what vehicle size you need
    description:
      - We also specialise in the movement of high value and fragile goods.
