message: "Today we start building the first pus/sass website"
meta:
  title: Speed4Courier
  description: Salut
form:
  top:
    formTitle: Speed4Courier
    formID: V1JRDgaa
    goTo:
      label: Get a Quote
      id: p4j1eU4x
    formDescription: We can move anything for you, from a small packet to multiple pallets.
  bottom:
    formTitle: Same Day Couriers
    formID: p4j1eU4x
    goTo:
      label: Request a Callback
      id: V1JRDgaa
    formDescription: Get a fast and reliable same-day courier service
content:
  contentKeyList:
    - home
    - about
    - fleet
    - services
    - quote
  services:
    description:
      - Same Day Courier Services
      - European Same Day Courier
      - Urgent Courier Service
      - Emergency Courier
      - Same Night Courier Service
      - Time Critical Courier
      - Over Night Dedicated
      - International Courier
      - Wait And Return Courier
      - Dedicated Direct Drive Delivery
      - Secure Courier Service
      - Refrigerated Courier Service
      - Exhibition and Event Courier
  about:
    title: We can move anything
    description:
      - Founded in Manchester in 2020, Speed4courier has grown to become one of the north's leading Same Day couriers.
      - The group runs an extensive fleet of vans and wagons, with strong presence across the North's major towns & cities and the M62 corridor.
      - We have long standing relationships in place with many of the UK's leading transport  firms.
  fleet:
    title: Please choose what vehicle size you need
    description: We also specialise in the movement of high value and fragile goods.
    vehicle:
      - title: Small Van (SV)
        length: 120cm
        width: 100cm
        height: 100cm
        payload: 450kg
        description: Carries 1 Standard UK Pallet

      - title: Short Wheel Based Van (SWB)
        length: 240cm
        width: 100cm
        height: 120cm
        payload: 800kg
        description: Carries 2 Standard UK Pallets

      - title: Long Wheel Based Van (LWB)
        length: 340cm
        width: 120cm
        height: 180cm
        payload: 1200kg
        description: Carries 3 Standard UK Pallets

      - title: Extra-Long Wheel Based Van (XLWB)
        length: 420cm
        width: 120cm
        height: 180cm
        payload: 1000kg
        description: Carries 4 Standard UK Pallets

      - title: Luton Van
        length: 400cm
        width: 200cm
        height: 200cm
        payload: 1000kg
        description: Carries 6 Standard UK Pallets Box, Curtain and Tail Lift Options Available

      - title: 7.5 Tonne (7.5T)
        length: 240cm
        width: 100cm
        height: 120cm
        payload: 800kg
        description: Carries 10 Standard UK Pallets Box, Curtain and Tail Lift Options Available

      - title: 18 Tonne (18T)
        length: 700cm
        width: 240cm
        height: 250cm
        payload: 9000kg
        description: Carries 14 Standard UK Pallets Box, Curtain and Tail Lift Options Available

      - title: 26 Tonne (26T)
        length: 800cm
        width: 240cm
        height: 250cm
        payload: 15000kg
        description: Carries 16 Standard UK Pallets Box, Curtain and Tail Lift Options Available

      - title: Artic
        length: 1360cm
        width: 250cm
        height: 260cm
        payload: 26000kg
        description: Carries 26 Standard UK Pallets Box,Curtain and Tail Lift Options Available
  # TermsAndConditions:

  # PrivacyPolicy:
  #     - This privacy policy sets out how Quickline Couriers Limited uses and protects any information that you give Quickline Couriers Limited when you use this website.

  #     - Quickline Couriers limited is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement.

  #     - Security
  #     - We are committed to ensuring that your information is secure. In order to prevent unauthorised access or disclosure, we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online.

  #   - How we use cookies:

  #     - A cookie is a small file which asks permission to be placed on your computer’s hard drive. Once you agree, the file is added, and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, like and dislikes by gathering and remembering information about your preferences.

  #     - Our website and services use cookies to distinguish you from other users of our services and to provide increased functionality when you are using our services. This helps us to provide you with a good experience when you browse our website and also allows us to improve our website and our services.

  #     - Unless you have adjusted your browser settings (where possible) to refuse cookies, our systems will issue cookies as soon as you visit our website or access other services. If you have switched off cookies, then some of the functionality of our services may not be available to you.

  #     - The cookies that we use on our website only collect anonymous information to optimise our services and do not collect personal information. The cookies we collect fall into the category of analytical cookies. Analytical cookies allow us to recognise and to count the number of visitors to our website, to see how visitors move around the website when they are using it and to record which content viewers view and are interested in. This helps us to determine how frequently particular pages and advertisements are visited and to determine the most popular areas of our website and/or services. This helps us to improve the service which we offer to you by helping us make sure our users are finding the information they are looking for, and by tracking the success of advertising campaigns on our website. Visit our cookie policy.

  #   - Links to other websites:

  #     - Our website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.

  #   - Controlling your personal information:
  #     - We will not sell, distribute or lease your personal information to third parties except to our invoice finance provider and bank or unless we have your permission or are required by law to do so. We may use your personal information to send you promotional information about third parties which we think you may find interesting if you tell us that you wish this to happen.

  #     - If you enter you email address into any of the contact forms on our website, you are automatically agreeing to opt-in to receive mailing from us about our services. Your email address will NOT be passed onto any third parties.

  #     - You may request details of any personal information which we hold about you under the Data Protection Act 1998. A small fee will be payable. If you would like a copy of the information held on you please contact us, and we will get in-touch.

  #     - If you believe that any information, we are holding on you is incorrect or incomplete, please contact us as soon as possible. We will promptly correct any information found to be incorrect.
